version: "3"
services:
  web:
    image: books4u-deploy
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.3"
          memory: 300M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
      - "8080:8080"
      - "8000:8000"
    networks:
      - webnet
networks:
  webnet:
