# Generated by Django 2.0.1 on 2018-02-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books4u', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='permission',
        ),
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.ManyToManyField(to='books4u.Permission'),
        ),
    ]
