# Generated by Django 2.0.1 on 2018-02-12 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books4u', '0002_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_firm',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bookcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
