# Generated by Django 2.1 on 2018-02-22 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books4u', '0003_auto_20180212_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.TextField(default='https://vignette.wikia.nocookie.net/arthur/images/a/a7/No_Image.jpg/revision/latest?cb=20130610195200'),
            preserve_default=False,
        ),
    ]
