# Generated by Django 2.0.1 on 2018-03-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books4u', '0004_book_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='permission',
        ),
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.CharField(choices=[('normal', 'normal'), ('banned', 'banned'), ('moderator', 'moderator')], default='normal', max_length=20),
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
