# Generated by Django 2.0.2 on 2018-03-25 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books4u', '0007_comment_report_counter'),
        ('books4u', '0007_review_liked_counter'),
    ]

    operations = [
    ]
